from aiogram.types import ReplyKeyboardMarkup, KeyboardButton, ReplyKeyboardRemove

b1= KeyboardButton('/start')
b2= KeyboardButton('Осмотреться')
b3= KeyboardButton('Попробовать открыть двери в помещении')
b4= KeyboardButton('Пойти вперед по коридору')
b5= KeyboardButton('Попробовать открыть окно')
b6= KeyboardButton('Попробовать открыть какую-то из ближайших дверей')
b7= KeyboardButton('Пойти дальше по коридору')
b8= KeyboardButton('Сдернуть скотч с двери и попробовать ввести код')
b9= KeyboardButton('Проигнорировать дверь и пойти дальше')
b10= KeyboardButton('Снова попробовать ввести код ')
b11= KeyboardButton('1899')
b12= KeyboardButton('9898')
b13= KeyboardButton('1234')
b14= KeyboardButton('0000')
b15= KeyboardButton('Пойти в дверь с надписью “Выход” ')
b16= KeyboardButton('Подойти к двери с кодовым замком')
b17= KeyboardButton('Побежать вперед, к выходу')
b18= KeyboardButton('Побежать в ближнюю дверь справа')
b19= KeyboardButton('Побежать в дальнюю дверь справа ')
b20= KeyboardButton('Побежать к лифту')
b21= KeyboardButton('Побежать в проход слева')
b22= KeyboardButton('Пойти в дальнюю дверь справа')
b23= KeyboardButton('Пойти в ближнюю дверь справа')
b24= KeyboardButton('Пойти в дальнюю дверь слева')
b25= KeyboardButton('Пойти в ближнюю дверь слева')
b26= KeyboardButton('Пойти в туалет')
b27= KeyboardButton('Побежать направо')
b28= KeyboardButton('Побежать налево')
b31= KeyboardButton('Пойти на выход')
b32= KeyboardButton('Подойти к карте ')
b33= KeyboardButton('Коснуться главного здания')
b34= KeyboardButton('Коснуться 9 корпуса')
b35= KeyboardButton('Пойти на лестницу')
b36= KeyboardButton('Пойти направо')
b37= KeyboardButton('Пойти налево')
b38= KeyboardButton('Подняться')
b39= KeyboardButton('Спуститься')
b40= KeyboardButton('Вернуться на этаж')
b41= KeyboardButton('Побежать наверх')

kb_client = ReplyKeyboardMarkup()
kb_client2 = ReplyKeyboardMarkup(one_time_keyboard=True)
kb_client3 = ReplyKeyboardMarkup()
kb_client4 = ReplyKeyboardMarkup()
kb_client5 = ReplyKeyboardMarkup()
kb_client6 = ReplyKeyboardMarkup()
kb_client7 = ReplyKeyboardMarkup(one_time_keyboard=True)
kb_client8 = ReplyKeyboardMarkup(one_time_keyboard=True)
kb_client9 = ReplyKeyboardMarkup(one_time_keyboard=True)
kb_client10 = ReplyKeyboardMarkup(one_time_keyboard=True)
kb_client11 = ReplyKeyboardMarkup(one_time_keyboard=True)
kb_client12 = ReplyKeyboardMarkup(one_time_keyboard=True)
kb_client13 = ReplyKeyboardMarkup()
kb_client14 = ReplyKeyboardMarkup(one_time_keyboard=True)
kb_client15 = ReplyKeyboardMarkup()
kb_client16 = ReplyKeyboardMarkup(one_time_keyboard=True)
kb_client17 = ReplyKeyboardMarkup(one_time_keyboard=True)

kb_client.add(b1)
kb_client2.add(b2)
kb_client3.add(b3).add(b4)
kb_client4.add(b5).add(b6).add(b7)
kb_client5.add(b8).add(b9)
kb_client6.add(b10).add(b9)
kb_client7.add(b11).add(b12).add(b13).add(b14)
kb_client8.add(b15).add(b16)
kb_client9.add(b17).add(b18).add(b19).add(b20).add(b21)
kb_client10.add(b22).add(b23).add(b24).add(b25).add(b26)
kb_client11.add(b27).add(b28)
kb_client13.add(b31).add(b32)
kb_client14.add(b33).add(b34)
kb_client15.add(b35).add(b36).add(b37)
kb_client16.add(b38).add(b39)
kb_client17.add(b40).add(b41)